# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-26 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('landing_image', models.ImageField(null=True, upload_to='images/')),
                ('screenshot_1', models.ImageField(null=True, upload_to='images/')),
                ('screenshot_2', models.ImageField(null=True, upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('site_link', models.CharField(max_length=200, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
